export default {
    messages: {
        // 登陆
        logContent1: "Scan to follow and log into the system.",
        logContent2: "Logging in with WeChat means you agree to the Terms of Service and Privacy Policy.",
        logContent3: 'By logging in in tourist mode, you agree to the Terms of Service and Privacy Policy.',
        logContent4: 'Tourist mode, click to enter',
        logContent5:'Scan Code Login',
        logContent6:'Tourist Pattern',
        logContent7:'Start Using',
        // 提交检测页
        submit: 'Submit',
        templateSelection: 'Template Selection',
        tips1: 'Tips: You can only enter 10 PMids, 1 per line',
        tips2: 'Tips: Only 20 PMids can be entered in an Excle file',
        tips3: 'Tips: zip compression file maximum 100M',
        downloadTemp: 'Please click Download upload template',
        inputPmid: 'Please input PMID',
        clickentersample:'Click Enter Sample',
        tips4: 'Drag the file here, or',
        tips5: ' click Add File',
        tips6: 'Only xls and xlsx files can be uploaded',
        tips7: 'Only zip and pdf files can be uploaded',
        // 报告列表页
        report: 'Report',
        index: 'Index',
        subType: 'Type',
        templateTest: 'Template',
        title: 'Title',
        author: 'Author',
        status: 'Status',
        collect: 'Collect',
        analyze: 'Analyze',
        submissionTime: 'Submit Time',
        sompletionTime: 'Complete Time',
        remainingTime: 'Remaining Time',
        operation: 'Operation',
        button_show: 'Org:PubMed',
        button_report: 'Report',
        button_down: 'Download',
        button_delete: 'Delete',
        button_collect: 'Collect',
        search: 'Search',
        reset: 'Refresh',
        download_tip: 'Contains rendering reports and entity information reports',
        batchDownload: 'Batch Download',
        batchDownloadTip: 'Please check if the report is selected before bulk download',
        returnReportList:'Return Report List',

        // 模版列表页
        templatetip: 'Custom (keyword/regular expression) matching templates (templates)',
        template: 'Template',
        button_copy: 'Copy',
        button_edit: 'Edit',
        button_dele: 'Delete',
        button_add: 'Add',
        button_confirm: 'Confirm',
        button_quit: 'Quit',
        templateName: 'Name',
        templatType: 'Type',
        templateDesc: 'Description',
        templateCreateTime: 'Creation Time',
        templateUpdataTime: 'Update Time',
        importFile: 'File import',
        customTemplate: 'Custom template',
        customSmallTemplate: 'Custom small template',
        smallTempName: 'Small Template Name',
        smallTempType: 'Small Template Type',
        smallTempTypeRegex: 'Regex',
        smallTempTypeEnumerate: 'Enum',
        matchEntry: 'Match Entry',
        note: 'Note',
        editName: 'Name',
        editDelete: 'Delete',
        getMore: 'Get More',
        // 报告导出页
        output: 'Output',
        // 收藏夹页
        favorites: 'Favorites',
        collectionMethod: 'Method',
        collectionContent: 'Content',
        button_details: 'Details',
        button_uncollect: 'Uncollect',
        button_download: 'Download',
        button_downloads: 'Batch Download',
        favoritesList: 'Favorites List',
        newFavorites: 'New Favorites',
        editMessage: 'Edit Message',
        deleteFavorites: 'Delete',
        favoritesInformation: 'Favorites Information',
        favoritesName: 'Favorites Name',
        addToFavorites: 'Add to Favorites',
        button_Collect: 'Collect',
        favoritesSysName: 'System favorites',
        createFavoritesTips:'Please fill in the name of your favorites',

        // 联系我们
        connect: 'Connect',
        // 帮助
        help: 'Help',
        return: 'Back',
        whatismedseeker_title: 'What is Medseeker?',
        whatismedseeker_title2: 'Medseeker',
        viewSampleReport1:'ViewSampleReport 1',
        viewSampleReport2:'ViewSampleReport 2',
        whatismedseeker_content1: "Welcome to MedSeeker, an online platform specifically designed for pathogenicity rating tasks of genetic variants. It strictly follows the ACMG guidelines and helps you effortlessly extract relevant evidence from biomedical literature.",
        whatismedseeker_content2: "MedSeeker integrates multiple powerful functions, including network literature retrieval, intelligent document parsing, personalized configuration, named entity recognition, result visualization, and batch data processing. Here, you can:",
        whatismedseeker_content3: "1. Highlight entities in literature: The platform automatically marks critical information in the literature for your easy comprehension.",
        whatismedseeker_content4: "2. Organize key data: Regardless of how scattered the literature is, MedSeeker can help you collect and organize the essential data effortlessly.",
        whatismedseeker_content5: "3. One-click export: You can export the organized data anytime for further use.",
        whatismedseeker_content6: "4. Flexible interaction and intuitive display: Enhance your efficiency through a concise interface and straightforward data visualization.",
        whatismedseeker_content7: "5. Reduce manual workload: MedSeeker's intelligent design significantly minimizes the time and effort required for manually searching for literature evidence.",
        // 详情页
        whatismedseeker_detail_title: 'Introduction to MedSeeker platform',
        whatismedseeker_content8: "MedSeeker is a professional online platform tailored for pathogenicity rating tasks of genetic variants. Based on ACMG guidelines, it aims to automate the extraction of relevant evidence from biomedical literature.",
        whatismedseeker_content9: "This platform integrates several robust features, including network literature retrieval, intelligent document parsing, custom configuration, named entity recognition, result visualization, and batch processing. MedSeeker automates the collection and organization of key data scattered across various literature sources. Through a flexible interactive interface and intuitive presentation, it significantly improves data extraction efficiency and accuracy, thereby reducing manual operation burdens.",
        whatismedseeker_content10: "In the field of genetic variant interpretation, MedSeeker’s value is particularly remarkable. Its main contributions include:",
        whatismedseeker_content11: "(1) An integrated framework for literature collection, analysis, and 'Literature Tree' structured storage: This framework is highly scalable and efficiently manages and utilizes literature resources.",
        whatismedseeker_content12: "(2) User-driven custom configuration and data mining framework: MedSeeker allows users to flexibly configure the platform according to their needs, meeting diverse data mining requirements.",
        whatismedseeker_content13: "(3) An integrated online literature data mining platform: MedSeeker provides a convenient and efficient solution for online literature data mining.",
        whatismedseeker_content14: "In conclusion, MedSeeker, with its powerful features and unique contributions, offers a robust tool for pathogenicity rating tasks of genetic variants. The platform architecture is outlined below:",
        whatismedseeker_content15: "The MedSeeker platform consists of two main modules: the ECPS LitTree module and the CRC module. Here’s a simple introduction to their functions and uses.",
        whatismedseeker_content16: "1. ECPS LitTree Module",
        whatismedseeker_content17: "This module acts like a super-intelligent literature assistant. Using a method called 'Literature Tree,' it enables efficient literature processing. By submitting a PMID (a unique identifier for literature), an Excel file containing PMIDs, or pre-downloaded PDF documents or their compressed packages, the module can perform the following operations:",
        whatismedseeker_content18: "(a) Literature collection: The assistant will fetch open-source PDF literature from the web based on the PMIDs you provide and securely store them in cloud storage, ensuring the safety of your documents.",
        whatismedseeker_content19: "(b) Literature parsing: The assistant will 'deeply analyze' these PDF documents, organizing the content, such as text and images, into a more comprehensible format (semi-structured JSON data) and storing it in a MySQL database. This allows for easier search and utilization of the information.",
        whatismedseeker_content20: "2. CRC Module",
        whatismedseeker_content21: "This module is a highly flexible tool for demand configuration and data mining. It comprises two parts:",
        whatismedseeker_content22: "(c) Demand configuration and data mining: Here, you can customize a data mining template according to your requirements. For instance, you can specify what information to extract from literature and how to display it. Once the template is set, the system will automatically mine the data as per your configuration.",
        whatismedseeker_content23: "(d) Result display and operations: After mining is completed, MedSeeker provides various forms of data visualization, such as tables and charts. You can also bookmark, export, and analyze these results according to your needs.",
        whatismedseeker_content24: "MedSeeker Features:",
        whatismedseeker_content25: "Literature data annotation: MedSeeker provides robust literature data annotation features. It can swiftly mine and annotate critical information in literature, such as genes, diseases, variants, experimental details, phenotypic data, pedigree charts, and transcript IDs. You can submit literature data in the form of PMIDs (unique identifiers for literature) or PDF files to enjoy an interactive online reading experience. For more details on how to submit literature data, please refer to the [Submit Detection] help interface.",
        whatismedseeker_content26: "Report generation: When you submit literature data mining tasks on the MedSeeker platform, the system generates a detailed report showcasing the mining results. This helps you better understand and utilize the literature data.",
        whatismedseeker_content27: "Data mining configuration: To help you pinpoint evidence in literature more accurately, MedSeeker offers flexible data mining configuration features. You can specify the content to be mined by adding keywords or regular expressions. This allows MedSeeker to quickly locate and annotate critical information based on your requirements. For more details on how to configure data mining, please refer to the [Template List] help interface.",
        whatismedseeker_content28: "Data bookmarking and export: On the MedSeeker platform, you can easily bookmark annotated literature data. Bookmarked content is stored in your Favorites, allowing for easy access and management. Additionally, you can categorize and export bookmarked data into Excel files for subsequent analysis and processing. For more details on how to bookmark and export data, please refer to the [Favorites] help interface.",
        whatismedseeker_content41: "The literature detection report is as follows:",
        whatismedseeker_content29: "The MedSeeker platform’s report is divided into six main sections, helping you easily browse and manage literature data:",
        whatismedseeker_content30: "(1) Tab bar: Centralizes various functions and settings for easy access to tools.",
        whatismedseeker_content31: "(2) Sections index: Quick navigation of article content. Simply click to jump to specific sections of the document, providing a smooth reading and convenient operation experience.",
        whatismedseeker_content32: "(3) Literature content: Displays detailed content and annotated evidence from the literature, helping you accurately grasp research highlights.",
        whatismedseeker_content33: "(4) Language switching: Supports multiple language options for personalized reading needs.",
        whatismedseeker_content34: "(5) Annotation categories: Adjust the entity categories for annotations. Selected categories will appear in corresponding colors in the text, helping you quickly differentiate information.",
        whatismedseeker_content35: "(6) Statistics: Displays identified entities and their occurrences in the document, providing a comprehensive understanding of the literature data.",
        whatismedseeker_content36: "The annotated data in the Literature Content section can be bookmarked, as shown below.",
        whatismedseeker_content37: "There are two ways to bookmark content:",
        whatismedseeker_content38: "(1) Free mouse selection: Select the desired content with your mouse to quickly add it to your Favorites.",
        whatismedseeker_content39: "(2) Click the star icon: Find the star icon at the end of the paragraph and click it to bookmark the section.",
        whatismedseeker_content40: "Bookmarked content will be centrally stored in the Favorites page for easy viewing, management, and data export.",
        whatismedseeker_content42: "As shown in the motivation diagram: ",
        // 导航按钮
        navigation: 'Navigation',
        platform_introduction: 'Platform Introduct',
        function_module: 'Function Module',
        function_introduction: 'Function Introduct',
        report_composition: 'Report Composite',
        collection_method: 'Collection Method',


        detection_title: 'Submit for Detection',
        detection_detail_title: 'Submit for Detection',
        // 详情页
        detection_content1: "The Submit Detection function allows you to submit literature data for deep mining and annotation by the platform. The operation steps are as follows:",
        detection_content2: "Step 1: Select submission method:",
        detection_content3: "PMID Submission: If you have the PMID (unique identifier) of the literature, you can directly input or upload a list containing PMIDs.",
        detection_content4: "EXCEL Submission: If you have multiple PMIDs, organize them into an EXCEL file and upload the file.",
        detection_content5: "PDF Submission: If you have the PDF files of the literature, you can directly upload single or multiple PDF files, or compress multiple PDF files into a .ZIP file for upload.",
        detection_content6: "Step 2: Submit literature data:",
        detection_content7: "Submit the corresponding file based on your selection. For example:",
        detection_content8: "If you selected PMID submission, enter the PMIDs.",
        detection_content9: "If you selected EXCEL submission, upload the EXCEL file containing the PMIDs.",
        detection_content10: "If you selected PDF submission, upload the PDF files or the .ZIP file.",
        detection_content11: "Step 3: Select a template:",
        detection_content12: "The template is an essential tool that guides the MedSeeker platform in mining and annotation. The system provides and uses a built-in template by default, which includes the following ten categories of information: Gene, Transcript ID, Reference Genome Version, Experiment Data, Disease chpo, Disease icd10, Species, Phenotype, Variant, Negative/Positive, Pedigree Information.",
        detection_content13: "If you need to adjust or add categories of information to be mined, you can edit them in the [Template List] interface. The MedSeeker platform will then conduct deep mining and annotation of the literature data based on your template requirements.",
        // 导航按钮
        submit_for_testing: 'Submit',
        select_submit_type: 'Submit Type',
        select_literature_data: 'Literature Data',
        select_template: 'Select Template',

        reportlist_title: 'Report List',
        reportlist_content1: "The report list is an important feature of the MedSeeker platform. It displays detailed information about the literature detection tasks you have submitted. After submitting a task on the [Submit Detection] interface, you will be automatically redirected to this page. Each row represents a literature task, including submission method, template used, article PMID, title, author, task progress, and time-related information.",
        reportlist_content2: "1. Quick Retrieval:",
        reportlist_content3: "By entering the PMID, you can quickly find the specified literature mining tasks.",
        reportlist_content4: "Click the 'Reset' button to restore and display all task lists.",
        reportlist_content5: "2. Bulk Operation:",
        reportlist_content6: "Select multiple tasks, then click the 'Bulk Download' button in the top right corner to download the literature report data of these tasks all at once.",
        reportlist_content7: "3. Template Information:",
        reportlist_content8: "This section displays the template details used in the current task, helping you understand the content being mined.",
        reportlist_content9: "4. Paper Information:",
        reportlist_content10: "Displays the basic information of the literature such as PMID, title, and author, making it easy for you to identify.",
        reportlist_content11: "5. Status and Progress:",
        reportlist_content12: "Provides the current completion progress of the task, so you can keep track of the task's status at any time.",
        reportlist_content13: "6. Time Information:",
        reportlist_content14: "Shows the task's creation and completion time, helping you understand the task timeline.",
        reportlist_content15: "7. Operation on the Results:",
        reportlist_content16: "For completed tasks, you have four operation options:",
        reportlist_content17: "Org: PubMed: View detailed information of the literature on the PubMed website.",
        reportlist_content18: "Report: View the system-generated literature report to understand the mining results.",
        reportlist_content19: "Download: Download the generated report data, including the HTML report file and annotated data in an EXCEL file.",
        reportlist_content20: "Delete: Delete the task record. Note that once deleted, the record cannot be recovered. Please proceed with caution.",
        reportlist_content21: "Quick retrieval: Provides quick retrieval of tasks by PMID, and clicking the Reset button restores the display of all task lists.",
        reportlist_content22: "Operation on the results: Provides four operation options for completed tasks: Org: PubMed to view detailed information of the literature on PubMed:",
        reportlist_content23: "Report: View the system-generated literature report.",
        reportlist_content24: "Download: Download the generated report data (including HTML report files and EXCEL files with annotated data).",
        reportlist_content25: "EXCEL file data example:",
        reportlist_content26: "Delete: Delete the task record. Once deleted, it cannot be recovered. Please proceed with caution.",
      

        // 导航按钮
        Quick_Retrieval: 'Quick Retrieval',
        Bulk_Operation: 'Bulk Operation',
        Template_Information: 'Template Information',
        Paper_Information: 'Paper Information',
        Status_and_Progress: 'Status Progress',
        Time_Information: 'Time Information',
        Operation_on_the_Results: 'Operation Results',

        templatelist_title: 'Template List',
        templatelist_content1: "Each template includes a set of content categories that users want to extract. The system's default template contains ten categories: Gene, Transcript ID, Reference Genome Version, Experiment Data, Disease chpo, Disease icd10, Species, Phenotype, Variant, Negative/Positive, and Pedigree Information. After submission, MedSeeker will mine and annotate the information of these categories in the submitted literature.",
        templatelist_content2: "Users can customize and edit templates on this interface to create new templates, enabling the import and extraction of information tailored to individual needs. The editable information includes:",
        templatelist_content3: "1. Mining Content: By adding keywords or regular expressions, you can create new templates and specify the information to be extracted and annotated.",
        templatelist_content4: "2. Marking Color: You can set different marking colors for each category to make the information clearer in the report.",
        templatelist_content5: "3. Tag Category: If you need to expand category information, you can add it here.",
        templatelist_content6: "4. Category Switch: This toggle option allows you to disable the annotation of a specific category if it is not needed.",
        templatelist_content7: "On the homepage, you can view the list of templates you own. Each row displays a template's index, name, type, description, creation and update time, and operation options:",
        templatelist_content8: "The operation options mainly provide customization functionalities:",
        templatelist_content9: "Edit: Edit the current template.",
        templatelist_content10: "Copy: Copy the information of the current template to create an editable duplicate (system default templates cannot be edited directly but can be copied for editing).",
        templatelist_content11: "Delete: Delete the current template (system default templates cannot be deleted).",
        templatelist_content12: "(1) Template information editing: You can edit the template's name and description.",
        templatelist_content13: "(2) Batch import information: To import large amounts of information, download the import template, fill it out as required, and click the 'File Import' button for quick import.",
        templatelist_content14: "(3) Category editing area: In the category editing area, you can edit the color, toggle activation, and content of each category (for the ten system-provided categories, only color and activation can be edited).",
        templatelist_content15: "Adding new matching category information:",
        templatelist_content16: "(1) Add: Click to add a new entry.",
        templatelist_content17: "(2) Category information: The 'Small Template Name' is the category name, and 'Small Template Type' specifies the matching type: 'Enum' for keyword matching and 'Regex' for regular expression matching.",
        templatelist_content18: "(3) Depending on the type chosen in (2), fill in the 'Match Entry' column with the relevant information ('Enum' requires keywords, and 'Regex' requires your regular expression; note that the system does not validate the correctness of regular expressions). The 'Note' column is for additional comments. Finally, click 'Add' to confirm and add the entry.",
        templatelist_content19: "Click 'Confirm' to complete the category extension.",
        templatelist_content20: "After editing and saving a template, you can view it in the [Template List]. In the [Submit Detection] interface, select the template you wish to use for literature mining tasks.",
        templatelist_content21: 'Template Categories and Operations',
        templatelist_content22: 'Customization of Mining Content',
        templatelist_content23: 'Template Personalization Settings',

        // 导航按钮
        custom_templates: 'Custom Template',
        editing_template: 'Editing Template',
        new_template: 'New Template',
        categoriesoperations: 'Type Operations',
        miningcontent: 'Data Mining',
        personalizationsettings: 'Personalization',

        // 收藏帮助页
        favorites_title: 'Favorites',
        favorites_content: 'The favorites interface is used to view and manage saved content, displaying information such as article name, PMID, saving method, and content. It supports viewing the original report, bulk exporting to Excel files, and removing items from favorites, among other operations.',
        favorites_content1: "Users can bookmark literature content and annotation data directly in the report interface:",
        favorites_content2: "Collection method",
        favorites_content3: "(1) Manually selecting content with the mouse.",
        favorites_content4: "(2) Clicking the star icon at the end of a paragraph.",
        favorites_content5: "Bookmarked content can be viewed and managed in the [Favorites] interface, where users can access article names, PMIDs, bookmarking methods, and the content itself. The interface also supports viewing the original report, batch exporting to Excel files, and unbookmarking.",
        favorites_content6: "(1) Favorites list: Displays a list of bookmarks. If users have customized multiple favorites folders, they can view and manage them here.",
        favorites_content7: "(2) Content: Shows details of the bookmarked content, including PMID, article name, author, bookmarking method, and content.",
        favorites_content8: "(3) Operation options: Offers functionalities such as view details, view report, export, and unbookmark.",
        favorites_content9: "View details: Displays the full information of the bookmarked content (truncated portions will be revealed).",
        favorites_content10: "View report: Opens the detection report of the article where the bookmarked content is located.",
        favorites_content11: "Export: Allows batch export of bookmarked content to an Excel file for further data processing or analysis.",
        favorites_content12: "Unbookmark: Removes a bookmarked item from the favorites list. Once unbookmarked, the action cannot be undone, so proceed with caution.",
        favorites_content13: "The Favorites interface is a practical feature of the MedSeeker platform that allows you to view and manage your bookmarked content. Here, you can clearly see the title of each article, its PMID (PubMed Unique Identifier), the bookmarking method, and specific content. Additionally, it supports viewing the original report, batch exporting to Excel files, and unbookmarking.",
        favorites_content14: "1. Favorites List: This section displays all the favorites folders you have created. If you have customized multiple folders, they will be listed here for easy viewing and management.",
        favorites_content15: "2. Content: Under each favorites folder, you can see all the bookmarked content in it. This includes information such as the article's PMID, title, author, the method chosen for bookmarking, and the specific content.",
        favorites_content16: "3. Operation Options: Provides options for managing bookmarked content, including viewing details, viewing the report, exporting, and unbookmarking.",


        // 导航按钮
        collection_help_method: 'Collection Method',
        favorites_function: 'Favorites Function',


        // 导航下拉菜单
        selectLanguage: 'Select Language',
        language: 'English',
        personCenter: 'Person Center',
        PersonCenter_userId: 'User ID',
        PersonCenter_userSex: 'Gender',
        PersonCenter_userName: 'Nickname',
        PersonCenter_vipType: 'VIP Type',
        PersonCenter_vipOpneTime: 'VIP Activation Time',
        PersonCenter_vipEndTime: 'VIP Expiration Time',
        memberCenter: 'Member Center',
        logOut: 'Log Out',
        Unknown_Member_Type:'Unknown Member Type',
        Mega_Member:'Mega Member',
        Super_Member:'Super Member',
        Ordinary_Member:'Ordinary Member',
        sex_man:'Man',
        sex_woman:'Woman',

        // Elmessage提示
        message_success: 'Submitted successfully!',
        message_pmid_template: 'Enter PMID or select a matching template',

        message_file_success: "File submitted successfully!",
        message_file_error: "File not uploaded, data parsing failed, or no matching template selected!",

        message_pdf_error: "File upload or database insertion failed, please try again!",
        message_pdf_file_out_limit: "Zip file count exceeded limit, extracted file over 100MB, or extracted PDF files larger than 10MB!",
        message_pdf_select_temp: 'Please select a matching template!',
        message_pdf_upload: 'Please upload the file first!',
        mes_pdf_file_err: 'File upload failed!',

        mes_rep_del_suc: 'Deleted successfully!',
        mes_rep_del_err: 'Delete failed!',

        mes_tmp_copy: "Copy successful!",
        mes_tmp_copy_err: "Copy failed!",

        mes_tmp_creat_no_name: 'The template name cannot be empty!',
        mes_tmp_detection: 'Please check whether the template name, template type, and template description are complete.',
        mes_tmp_more_info: 'No further data available!',
        mes_tmp_tips: 'Tips',
        mes_tmp_del_tip: 'This operation will permanently delete the template. Do you want to continue?',
        mes_tmp_del_tip_yes: 'Yes',
        mes_tmp_del_tip_no: 'No',

        mes_fav_repeat: "Favorite name already exists!",
        mes_fav_add: "Added successfully!",
        mes_fav_add_err: 'Add failure!',
        mes_fav_modifind: "Modified successfully!",
        mes_fav_modifind_err: "Modification failed!",
        mes_fav_quit_collect: "Unfavorited successfully!",
        mes_fav_quit_collect_err: "Unfavorite failed!",
        mes_fav_collect_suc: "Favorited successfully!",
        mes_fav_collect_suc_err: "Favorite failed!",
        mes_fav_again_collect: "Failed to add to favorites, please try again...",

        mes_login_swaplang:'Language has been switched to English!'
    }
}