export default {
    messages: {
        // 登陆
        logContent1:'扫码关注，登录系统',
        logContent2:'微信登录即表示同意服务条款、隐私条款',
        logContent3:'以游客模式登录，即表示您同意本服务条款和隐私政策',
        logContent4:'游客模式，点击使用',
        logContent5:'扫码登陆',
        logContent6:'游客模式',
        logContent7:'开始使用',
        // 提交检测页
        submit: '提交检测',
        templateSelection: '模版选择',
        tips1: '温馨提示：只能输入10个PMID，每行1个',
        tips2: '温馨提示：1个Excle文件中只能输入20个PMID',
        tips3: '温馨提示：zip压缩文件最大100M',
        downloadTemp: '点击下载上传模版',
        inputPmid: '请输入PMID',
        clickentersample:'点击输入样例',
        tips4: '将文件拖到此处，或点击添加文件',
        tips5: '点击添加文件',
        tips6: '只能上传xls、xlsx文件',
        tips7: '只能上传zip、pdf文件',

        // 报告列表页
        report: '报告列表',
        index: '序号',
        subType: '提交方式',
        templateTest: '模版检测',
        title: '文章名',
        author: '作者',
        status: '状态',
        collect: '采集',
        analyze: '解析',
        submissionTime: '文章提交时间',
        sompletionTime: '报告生成时间',
        remainingTime: '剩余时间',
        operation: '操作',
        button_show: '来源:PubMed',
        button_report: '查看报告',
        button_down: '下载报告',
        button_delete: '删除报告',
        button_collect: '收藏',
        download_tip:'含有渲染报告和实体信息报告',
        search: '搜索',
        reset: '刷新',
        batchDownload: '批量下载',
        batchDownloadTip:'批量下载前请查看是否选中报告',
        returnReportList:'返回报告列表',

        // 模版列表页
        templatetip:'自定义(关键词/正则表达式)匹配模板(简称模板)',
        template: '模版列表',
        button_copy: '拷贝',
        button_edit: '编辑',
        button_dele: '删除',
        button_add: '新增',
        button_confirm: '确认',
        button_quit: '取消',
        templateName: '模版名称',
        templatType: '模版类型',
        templateDesc: '模版描述',
        templateCreateTime: '创建时间',
        templateUpdataTime: '更新时间',
        importFile: '导入',
        customTemplate:'自定义模版',
        customSmallTemplate:'自定义小模版',
        smallTempName:'小模版名称',
        smallTempType:'小模版类型',
        smallTempTypeRegex:'正则表达式',
        smallTempTypeEnumerate:'枚举',
        matchEntry:'匹配项',
        note:'备注',
        editName:'名称',
        editDelete:'删除',
        getMore:'获取更多',

        // 报告导出页
        output: '报告导出',
        // 收藏夹页
        favorites: '收藏夹',
        collectionMethod: '收藏方式',
        collectionContent: '内容',
        button_details: '查看详情',
        button_uncollect: '取消收藏',
        button_download: '导出',
        button_downloads: '批量导出',
        favoritesList: '收藏列表',
        newFavorites: '新建收藏夹',
        editMessage: '编辑信息',
        deleteFavorites: '删除',
        favoritesInformation:'收藏夹信息',
        favoritesName:'收藏夹名称',
        addToFavorites:'添加到收藏',
        button_Collect:'收藏',
        favoritesSysName:'系统默认收藏夹',
        createFavoritesTips:'请填写收藏夹名称',

        // 联系我们
        connect: '联系我们',

        // 帮助
        help: '了解我们',
        return:'返回',
        viewSampleReport1:'查看示例报告1',
        viewSampleReport2:'查看示例报告2',
        whatismedseeker_title:'MedSeeker是什么?',
        whatismedseeker_title2:'MedSeeker',
        whatismedseeker_content1:'欢迎使用MedSeeker，一个专为遗传变异致病性评级任务打造的在线平台，它严格遵循ACMG指南，帮助您轻松地从生物医学文献中挖掘相关证据。',
        whatismedseeker_content2:'MedSeeker平台集多种强大功能于一身，包括网络文献检索、智能文档解析、个性化配置、命名实体识别、结果可视化以及批量数据处理等。在这里，您可以：',
        whatismedseeker_content3:'1. 高亮标注文献实体：平台会自动为您标注出文献中的关键信息，让您一目了然。',
        whatismedseeker_content4:'2. 整理关键数据：无论文献多么分散，MedSeeker都能帮您轻松收集并整理其中的关键数据',
        whatismedseeker_content5:'3. 一键导出：整理好的数据，您可以随时导出，方便后续使用。',
        whatismedseeker_content6:'4. 灵活交互与直观展示：通过简洁明了的界面和直观的数据展示，提升您的工作效率。',
        whatismedseeker_content7:'5. 减轻人工负担：MedSeeker的智能化设计，大大减少了您手动寻找文献证据的时间和精力。',
        // 详情页
        whatismedseeker_detail_title:'MedSeeker平台简介',
        whatismedseeker_content8:'MedSeeker是一个专为遗传变异致病性评级任务设计的专业在线平台。它依据ACMG指南，致力于自动化地从生物医学文献中挖掘相关证据。',
        whatismedseeker_content9:'该平台集成了多项强大功能，包括网络文献检索、智能文档解析、自定义配置、命名实体识别、结果可视化以及批量处理。MedSeeker能够自动化地收集与整理分散在各类文献中的关键数据，并通过灵活的交互界面和直观的展示方式，极大地提升了数据提取的效率与准确性，从而减轻了人工操作的负担。',
        whatismedseeker_content10:'在遗传变异解读领域，MedSeeker的应用价值尤为突出。其主要贡献包括：',
        whatismedseeker_content11:'（1）一体化文献采集解析与“文献树”结构化存储框架：这一框架具备高度的扩展性，能够高效地管理和利用文献资源。',
        whatismedseeker_content12:'（2）用户驱动的自定义需求配置与数据挖掘框架：MedSeeker允许用户根据自身需求进行灵活配置，以满足多样化的数据挖掘需求。',
        whatismedseeker_content13:'（3）一体化的在线文献数据挖掘平台：MedSeeker平台的出现，为用户提供了一个便捷、高效的在线文献数据挖掘解决方案。',
        whatismedseeker_content14:'总之，MedSeeker凭借其强大的功能和独特的贡献，为遗传变异致病性评级任务提供了强有力的工具。MedSeeker的平台架构如下：',
        whatismedseeker_content15:'MedSeeker平台是一个功能强大的工具，它主要由两大模块组成：ECPS LitTree模块和CRC模块。接下来，我们会用简单易懂的语言，带你快速了解这两个模块的功能和用法。',
        whatismedseeker_content16:'一、ECPS LitTree模块',
        whatismedseeker_content17:'这个模块就像是一个超级智能的文献小助手，它采用了一种叫做“文献树”的方法，能够帮你高效地处理文献。你只需要提交文献的PMID（就是文献的唯一标识码）、包含PMID的Excel文件，或者你已经下载好的PDF文献及其压缩包，它就能帮你完成以下两步操作：',
        whatismedseeker_content18:'(a) 文献采集：小助手会根据你提供的PMID，去网上找到对应的开源文献PDF，并把它们安全地存放在云存储里，这样你就不用担心文献会丢失啦！',
        whatismedseeker_content19:'(b) 文献解析：接下来，小助手会对这些PDF文献进行“深度解读”，也就是把文献里的文字、图片等信息整理成一种更容易理解的格式（半结构化JSON数据），并存储在MySQL数据库中。这样，你就能更方便地查找和利用这些信息了。',
        whatismedseeker_content20:'二、CRC模块',
        whatismedseeker_content21:'这个模块是一个超级灵活的需求配置和数据挖掘小能手，它包含两个部分：',
        whatismedseeker_content22:'(c) 需求配置和数据挖掘：在这里，你可以根据自己的需求，定制一个专属的文献数据挖掘模板。比如，你想从文献中提取哪些信息、以什么样的格式展示等，都可以在这里进行设置。设置好模板后，系统就会按照你的要求，自动进行数据挖掘啦！',
        whatismedseeker_content23:'(d) 结果展示与操作：挖掘完成后，MedSeeker会为你提供多种形式的数据挖掘结果展示，比如表格、图表等。你还可以根据自己的需要，对这些结果进行收藏、导出等操作，方便你后续的分析和利用。',
        whatismedseeker_content24:'MedSeeker功能介绍：',
        whatismedseeker_content25:'文献数据标注：MedSeeker平台拥有强大的文献数据标注功能。它能够快速挖掘并标注文献中的关键信息，如基因、疾病、变异、实验信息、表型数据、家系图以及转录本号等。您只需通过PMID（文献唯一标识符）或PDF文件等形式提交文献数据，即可享受在线的交互式文献阅读体验。更多关于如何提交文献数据的详情，请查阅【提交检测】帮助界面。',
        whatismedseeker_content26:'检测报告生成：当您在MedSeeker系统上提交文献数据挖掘任务后，系统会为您生成一份详细的检测报告。这份报告将清晰地展示挖掘结果，帮助您更好地理解和利用文献数据。',
        whatismedseeker_content27:'挖掘数据配置：为了让您更精准地定位文献中的证据，MedSeeker提供了灵活的挖掘数据配置功能。您可以通过增加关键词或正则表达式的方式，来指定平台需要挖掘的内容。这样，MedSeeker就能根据您的需求，快速找到并标注出文献中的关键信息。更多关于如何配置挖掘数据的详情，请查阅【模板列表】帮助界面。',
        whatismedseeker_content28:'数据收藏导出：在MedSeeker平台上，您可以轻松地对标注的文献数据进行收藏。收藏的内容将会被放置在您的收藏夹中，方便您随时查看和管理。此外，您还可以对收藏的数据进行分类管理，并导出为Excel文件，以便进行后续的分析和处理。更多关于如何收藏和导出数据的详情，请查阅【收藏夹】帮助界面。',
        whatismedseeker_content29:'MedSeeker平台的报告分为六个主要部分，帮助您轻松浏览和管理文献数据：',
        whatismedseeker_content30:'（1）Tab栏：这里集中了界面内的各种功能和设置选项，让您轻松访问所需工具。',
        whatismedseeker_content31:'（2）Sections索引：文章内容的快速导航，只需点击即可跳转到文档的特定部分，阅读更流畅，操作更便捷。',
        whatismedseeker_content32:'（3）Literature content文献内容：展示文献的详细内容和标注的证据信息，助您精准把握研究要点。',
        whatismedseeker_content33:'（4）Language切换：支持多种语言切换，满足您的个性化阅读需求。',
        whatismedseeker_content34:'（5）Category注释类别：调整注释的实体类别，选中后，正文中将出现对应颜色的标注，帮助您快速区分不同信息。',
        whatismedseeker_content35:'（6）Statistic统计：显示已标识实体及其在文档中的出现次数，让您对文献数据有更全面的了解。',
        whatismedseeker_content36:'其中，Literature content中的文献内容与标注数据可进行收藏，如下图所示。',
        whatismedseeker_content37:'收藏方式有两种：',
        whatismedseeker_content38:'（1）鼠标自由选中收藏：直接用鼠标选中想要收藏的内容，即可快速添加至收藏夹。',
        whatismedseeker_content39:'（2）点击五角星收藏标志：在段落末尾找到五角星标志，点击即可收藏该段落。',
        whatismedseeker_content40:'收藏的内容将统一存放在收藏夹页面，方便您随时查看、管理和导出数据。',
        whatismedseeker_content41:'文献检测报告如下：',
        whatismedseeker_content42:'如动机图所示：',
        // 导航按钮
        navigation:'导航',
        platform_introduction:'平台介绍',
        function_module:'功能模块',
        function_introduction:'功能介绍',
        report_composition:'报告组成',
        collection_method:'收藏方式',

        detection_title:'提交检测',
        detection_detail_title:'提交检测',
        detection_content1:'提交检测功能，允许您提交文献数据，以便平台进行深度挖掘和标注。操作步骤如图：',
        detection_content2:'步骤1、选择提交方式：',
        detection_content3:'PMID提交：如果您有文献的PMID（文献唯一标识符），可以直接输入或上传包含PMID的列表。',
        detection_content4:'EXCEL提交：如果您有多个PMID，可以将其整理在EXCEL文件中，然后上传该文件。',
        detection_content5:'PDF提交：如果您有文献的PDF文件，可以直接上传单个或多个PDF文件，或者将多个PDF文件打包成.ZIP压缩包后上传。',
        detection_content6:'步骤2、提交文献数据：',
        detection_content7:'根据您的选择，提交对应的文件。例如：',
        detection_content8:'如果您选择了PMID提交，请输入PMID；',
        detection_content9:'如果您选择了PMID提交，请上传包含PMID的EXCEL文件；',
        detection_content10:'如果您选择了PDF提交，请上传文献的PDF文件或.ZIP压缩包。',
        detection_content11:'步骤3、选择模板：',
        detection_content12:'模板是指导MedSeeker平台进行挖掘标注的重要工具。系统默认提供并使用一个内置模板，该模板包含以下十个类别的信息：Gene（基因）、Transcript ID（转录本号）、Reference Genome Version（参考基因组版本）、Experiment Data（实验数据）、Disease chpo（疾病CHPO分类）、Disease icd10（疾病ICD-10分类）、Species（物种）、Phenotype（表型）、Variant（变异）、Negative/Positive（阴性/阳性结果）、Pedigree Information（家系信息）。',
        detection_content13:'如果您需要调整或添加挖掘的信息类别，可以在【模板列表】界面进行编辑。这样，MedSeeker平台将根据您的模板要求，对文献数据进行深度挖掘和标注。',
        // 导航按钮
        submit_for_testing:'提交检测',
        select_submit_type:'提交方式',
        select_literature_data:'文献数据',
        select_template:'选择模版',
        // 报告列表
        reportlist_title:'报告列表',
        reportlist_content1:'报告列表是MedSeeker平台的一个重要功能，它展示了您已提交的文献检测任务的详细信息。【提交检测】界面提交任务后，会自动跳转到该界面。每一行都代表一篇文献任务，包括提交方式、使用的模板、文章PMID、标题作者、任务进度及时间等信息。',
        reportlist_content2:'1.	快速检索（Quick Retrieval）：',
        reportlist_content3:'通过输入PMID，您可以快速找到指定的文献挖掘任务。',
        reportlist_content4:'点击“Reset”按钮，将恢复显示所有任务列表。',
        reportlist_content5:'2.	批量操作（Bulk Operation）：',
        reportlist_content6:'选择多个任务，然后点击右上角的“批量下载”按钮，即可一次性下载这些任务的文献报告数据。',
        reportlist_content7:'3.	模板信息（Template Information）：',
        reportlist_content8:'此处显示了当前任务所使用的模板详情，帮助您了解挖掘的内容。',
        reportlist_content9:'4.	文献信息（Paper Information）：',
        reportlist_content10:'展示了文献的PMID、标题、作者等基本信息，方便您快速识别。',
        reportlist_content11:'5. 状态与进度（Status and Progress）：',
        reportlist_content12:'提供了当前任务的完成进度，让您随时掌握任务状态。',
        reportlist_content13:'6. 时间信息（Time Information）：',
        reportlist_content14:'显示了任务的创建时间和完成时间，帮助您了解任务的时间线。',
        reportlist_content15:'7. 结果操作（Operation on the Results）：',
        reportlist_content16:'对于已完成的任务，您有四个操作选项：',
        reportlist_content17:'Org:PubMed：查看文献在PubMed网站上的详细信息。',
        reportlist_content18:'Report：查看系统生成的文献报告，了解挖掘结果。',
        reportlist_content19:'Download：下载生成的报告数据，包括HTML格式的报告文件和标注数据的EXCEL文件。',
        reportlist_content20:'Delete：删除该条任务记录，注意删除后不可恢复，请谨慎操作。',
        reportlist_content21:'Quick retrieval: 提供了通过PMID对任务实现快速的检索，点击Reset按钮可以恢复显示所有的任务列表。',
        reportlist_content22:'Operation on the results: 提供了对已完成任务的四个操作选项：Org:PubMed查看文献在PubMed网站的信息：',
        reportlist_content23:'Report查看系统生成的文献报告：',
        reportlist_content24:'Download对生成的报告数据进行下载（下载文件包含报告的HTML文件、标注数据的EXCEL文件）：',
        reportlist_content25:'EXCEL文件数据示例：',
        reportlist_content26:'Delete删除该条任务记录，删除后不可恢复，请谨慎操作。',
        // 导航按钮
        Quick_Retrieval:'快速检索',
        Bulk_Operation:'批量操作',
        Template_Information:'模板信息',
        Paper_Information:'文献信息',
        Status_and_Progress:'状态与进度',
        Time_Information:'时间信息',
        Operation_on_the_Results:'结果操作',
        // 模版列表
        templatelist_title:'模版列表',
        templatelist_content1:'每一个模板包含了一套用户要挖掘的内容信息，系统内置模板默认包含十个类别Gene, Transcript ID, Reference Genome Version, Experiment Data, Disease chpo, Disease icd10, Species, Phenotype, Variant, Negative/Positive, Pedigree Information，提交后MedSeeker会挖掘标注出提交文献中相关类别的信息。',
        templatelist_content2:'用户可在此界面通过自定义编辑模板从而组建新的模板，实现对个人需求信息的导入与挖掘。可编辑的信息如下：',
        templatelist_content3:'1. 挖掘内容（Mining Content）：通过添加关键词或正则表达式，您可以组建新的模板，并指定需要挖掘和标注的信息。',
        templatelist_content4:'2. 标注颜色（Marking Color）：您可以为每个类别设置不同的标注颜色，以便在报告中更清晰地查看信息。',
        templatelist_content5:'3. 类别标签（Tag Category）：如果您需要扩展类别信息，可以在此处进行添加。',
        templatelist_content6:'4. 类别开关（Category Switch）：这是一个开关选项。如果您不希望标注某个类别的信息，可以将其关闭。',
        templatelist_content7:'在首页，您可以查看个人拥有的模板列表。每一行都显示了一个模板的索引、名称、类型、描述、创建和更新时间，以及操作选项：',
        templatelist_content8:'操作选项主要提供对模板的自定义编辑功能：',
        templatelist_content9:'Edit: 编辑当前的模板；',
        templatelist_content10:'Copy: 复制当前模板的信息，得到一个可编辑的副本（系统内置模板不可直接编辑，但可复制后编辑）；',
        templatelist_content11:'Delete: 删除当前模板（注意，系统内置模板不可删除）。',
        templatelist_content12:'（1）Template information editing：可对模板的名称、描述信息进行编辑；',
        templatelist_content13:'（2）Batch import information：如果需要导入大量信息，可以下载信息导入模板，按要求填写后，点击“File Import”按钮快速导入；',
        templatelist_content14:'（3）Category editing area：在类别编辑区域，您可以对每个类别的颜色、是否启用以及内容进行编辑（系统提供的十个类别只能编辑颜色和是否启用）。',
        templatelist_content15:'新增匹配的类别信息：',
        templatelist_content16:'（1）Add：点击添加；',
        templatelist_content17:'（2）Category information：Small Template Name为类别的名称，Small Template Type为增加匹配的类型：Enum为关键词匹配，Regex为正则表达式匹配。',
        templatelist_content18:'（3）根据(2)选择的类别，在Match Entry列填入信息（Enum则填入关键词，Regex则填入自己编辑好的正则表达式，注意系统不会对正则表达式的正确性进行验证），Note列为备注信息，随后点击Add，确认添加一条信息。',
        templatelist_content19:'最后点击confirm确认即可完成类别的扩展。',
        templatelist_content20:'编辑并保存模板后，您可以在【模板列表】中查看。在【提交检测】界面，选择您希望使用的模板进行文献挖掘任务。',
        templatelist_content21:'模板类别与操作',
        templatelist_content22:'挖掘内容的定制',
        templatelist_content23:'模板个性化设置',
        // 导航按钮
        custom_templates:'定义模版',
        editing_template:'编辑模版',
        new_template:'新增模版',
        categoriesoperations: '模板类别与操作',
        miningcontent: '挖掘内容定制',
        personalizationsettings: '个性化设置',

        // 收藏夹
        favorites_title:'收藏夹',
        favorites_content1:'用户可在报告界面对文献内容和标注数据进行收藏：',
        favorites_content2:'收藏方式',
        favorites_content3:'（1）鼠标自由选中收藏。',
        favorites_content4:'（2）点击段落末尾的五角星收藏标志；',
        favorites_content5:'收藏的内容可在【收藏夹】界面查看与管理，查看文章名称、PMID、收藏方式及内容等信息。支持原报告查看、批量导出为Excel文件及取消收藏等操作。',
        favorites_content6:'（1）Favorites List: 显示了收藏夹列表信息，用户如果自定义了多个收藏夹，将会在这里显示与管理；',
        favorites_content7:'（2）Content:显示了收藏夹中的收藏内容的信息，包括PMID、文章名称、作者、收藏的方式和内容等信息；',
        favorites_content8:'（3）Operation Options：提供了操作选项，查看详情、查看报告、导出、取消收藏。',
        favorites_content9:'查看详情：即可查看收藏内容的全部信息（收藏内容信息的过长部分会被隐藏）；',
        favorites_content10:'查看报告：即可查看收藏内容所在文章的检测报告；',
        favorites_content11:'导出：支持将收藏夹中的内容批量导出为Excel文件，方便您进行后续的数据处理或分析：',
        favorites_content12:'取消收藏：如果您不再需要某个收藏内容，点击此选项可以将其从收藏夹中移除，取消收藏后不可恢复，请谨慎操作。',
        
        favorites_content13:'收藏夹界面是MedSeeker平台的一个实用功能，它允许您查看与管理您的收藏内容。在这里，您可以清晰地看到每篇文章的名称、PMID（PubMed唯一标识符）、收藏方式及具体内容等信息。此外还支持原报告查看、批量导出为Excel文件及取消收藏等操作。',
        favorites_content14:'1. Favorites List:此区域显示了您创建的所有收藏夹。如果您自定义了多个收藏夹，它们将在这里一一列出，方便您进行查看与管理。',
        favorites_content15:'2. Content: 在每个收藏夹下，您可以看到该收藏夹中的所有收藏内容。这些信息包括文章的PMID、名称、作者以及您收藏时选择的方式和具体内容。',
        favorites_content16:'3. Operation Options：提供了对收藏内容的操作选项，包括查看详情、查看报告、导出、取消收藏。',

        // 导航按钮
        collection_help_method:'收藏方式',
        favorites_function:'收藏夹功能',

        // 导航下拉菜单
        selectLanguage: '选择语言',
        language: '中文',
        personCenter: '个人中心',
        PersonCenter_userId:'用户ID',
        PersonCenter_userSex:'性别',
        PersonCenter_userName:'昵称',
        PersonCenter_vipType:'会员类型',
        PersonCenter_vipOpneTime:'会员开通时间',
        PersonCenter_vipEndTime:'会员到期时间',
        memberCenter: '会员中心',
        logOut: '退出',
        Unknown_Member_Type:'未知会员类型',
        Mega_Member:'大会员',
        Super_Member:'超级会员',
        Ordinary_Member:'普通会员',
        sex_man:'男',
        sex_woman:'女',

        // Elmessage所有的提示内容
        message_success:'提交成功！',
        message_pmid_template:'请输入PMID或选择匹配模板',

        message_file_success:'文件提交成功！',
        message_file_error:'未上传文件、文件数据解析失败或未选择匹配模板！',

        message_pdf_error:'文件上传或插入数据库失败，请重试！',
        message_pdf_file_out_limit:'压缩包文件数量超过限制、解压文件大于100M、解压后存在有pdf文件大于10M！',
        message_pdf_select_temp:'请选择匹配模板！',
        message_pdf_upload:'请先上传文件！',
        mes_pdf_file_err:'文件上传失败！',

        mes_rep_del_suc:'删除成功！',
        mes_rep_del_err:'删除失败！',

        mes_tmp_copy:'拷贝成功！',
        mes_tmp_copy_err:'拷贝失败！',
        mes_tmp_creat_no_name:'模版名不能为空！',
        mes_tmp_detection:'请检查模板名称、模板类型、模板描述是否是否输入完整！',
        mes_tmp_more_info:'暂无更多数据!',
        mes_tmp_tips:'提示',
        mes_tmp_del_tip:'此操作将永久删除该模板, 是否继续?',
        mes_tmp_del_tip_yes:'是',
        mes_tmp_del_tip_no:'否',

        mes_fav_repeat:'收藏夹重名!',
        mes_fav_add:'添加成功!',
        mes_fav_add_err:'添加失败',
        mes_fav_modifind:'修改成功',
        mes_fav_modifind_err:'修改失败',
        mes_fav_quit_collect:'取消收藏成功!',
        mes_fav_quit_collect_err:'取消收藏失败!',
        mes_fav_collect_suc:'收藏成功!',
        mes_fav_collect_suc_err:'收藏失败!',
        mes_fav_again_collect:'添加收藏夹失败，请重试...',

        // 新的帮助内容
        mes_login_swaplang:'语言已切换至中文!'

    }
}