server:
  port: 8083
  servlet:
    context-path: /analysis
  compression:
    enabled: true
    min-response-size: 1024

spring:
      #  datasource:
      #    url: jdbc:mysql://1.117.138.151:3306/lsv?useUnicode=true&characterEncoding=UTF8
      #    username: root
      #    password: tz123456...
      #    druid:
      #      initial-size: 5 # Connection pool initialization size
      #      min-idle: 10 # Minimum number of idle connections
      #      max-active: 20 #Maximum number of connections
      #      web-stat-filter:
      #        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #Do not count these request data
      #      stat-view-servlet: #Login username and password to access the monitoring web page
      #        login-username: druid...
      #        login-password: druid...
#spring:
  #  datasource:
  #    url: jdbc:mysql://1.117.138.151:3306/lsv?useUnicode=true&characterEncoding=UTF8
  #    username: root
  #    password: tz123456...
  #    druid:
  #      initial-size: 5 # Connection pool initialization size
  #      min-idle: 10 # Minimum number of idle connections
  #      max-active: 20 #Maximum number of connections
  #      web-stat-filter:
  #        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #Do not count these request data
  #      stat-view-servlet: #Login username and password to access the monitoring web page
  #        login-username: druid...
  #        login-password: druid...

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-8vb7w4mo8b6npnet2go.mysql.zhangbei.rds.aliyuncs.com:3306/analysis_module?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: LWcc123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

#  redis:
#    host: 127.0.0.1
#    database: 0
#    port: 6379
#    password:
#    jedis:
#      pool:
#        max-active: 8 # The maximum number of connections in the connection pool
#        max-wait: -1ms # Connection pool maximum blocking wait time (use a negative value to indicate no limit)
#        max-idle: 8 # Maximum idle connections in the connection pool
#        min-idle: 0 # min
#    timeout: 3000ms

logging:
  file:
    path: ./logs/analysis
#
#notify:
#  url: http://localhost:8082/api/admin/comm/notify?code=

staticResources:
  images:
    localPath: file:D:/imgs/
    localDirPath: D:/imgs/
    url: /images/**
    httpUrl: http://localhost:8081/api/admin/images
    #  redis:
    #    host: 127.0.0.1
    #    database: 0
    #    port: 6379
    #    password:
    #    jedis:
    #      pool:
    #        max-active: 8 # The maximum number of connections in the connection pool
    #        max-wait: -1ms # Connection pool maximum blocking wait time (use a negative value to indicate no limit)
    #        max-idle: 8 # Maximum idle connections in the connection pool
    #        min-idle: 0 # min
    #    timeout: 3000ms

    logging:
      file:
        path: ./logs/ask
    #
    #notify:
    #  url: http://localhost:8082/api/admin/comm/notify?code=

    staticResources:
      images:
        localPath: file:D:/imgs/
        localDirPath: D:/imgs/
        url: /images/**
        httpUrl: http://localhost:8081/api/admin/images
#spring:
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://119.8.26.72:5785/duoyun?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: YfTSXomY4Hjfa4P1
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#    serialization:
#      write-dates-as-timestamps: false
#
#
#logging:
#  file:
#    path: ./logs/dy/admin
#
#notify:
#  url: http://localhost:8082/api/admin/comm/notify?code=
#
#staticResources:
#  images:
#    localPath: file:/root/data/images/
#    localDirPath: /root/data/images/
#    url: /images/**
#    httpUrl: http://119.8.32.97:8081/api/admin/images
